server:
  port: 10103

spring:
  application:
    name: rocketmq-consumer
  cloud:
    stream:
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        input: {destination: test-topic, content-type: application/json,group: test-group}
      rocketmq:
        binder:
          namesrv-addr: 192.168.99.4:9876




