server:
  port: 9091

spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        output: {destination: test-topic, content-type: application/json}
      rocketmq:
        binder:
          namesrv-addr: 192.168.99.4:9876




